### ISSUE TITLE
Add boxes in PRA rooms

### ISSUE THREAD

**Issue by enceladus2000** [ERC-BPGC/echoslam_acoustics#1]
Write a method and example to programmatically generate a cuboid on the floor of a PRA room.

**Comment by enceladus2000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PRA boxes](https://trello.com/c/8VwVNDxl/100-pra-boxes)

**Comment by Ashutosh781** [comment]
box_make.py
